### PR TITLE
Added sk_to_pk() for Kem trait and implemented for dhkem

### LINKED ISSUE #36: Add option to convert Kem::PrivateKey to its matching Kem::PublicKey

### PR DESCRIPTION
**Pull request by ycscaly**
resolves #36

### CODE REVIEW

**Comment by rozbb** [comment]
I can't seem to push to your branch. Can you apply this diff before I merge?

```diff
diff --git a/src/kem/dhkem.rs b/src/kem/dhkem.rs
index 671270a..0ff960e 100644
--- a/src/kem/dhkem.rs
+++ b/src/kem/dhkem.rs
@@ -114,7 +114,7 @@ macro_rules! impl_dhkem {

                 // The encapped key is the ephemeral pubkey
                 let encapped_key = {
-                    let pk_eph = <$dhkex as DhKeyExchange>::sk_to_pk(&sk_eph);
+                    let pk_eph = <$kem_name as KemTrait>::sk_to_pk(&sk_eph);
                     EncappedKey(pk_eph)
                 };

@@ -198,11 +198,6 @@ macro_rules! impl_dhkem {
                 type PrivateKey = PrivateKey;
                 type EncappedKey = EncappedKey;

-                /// Computes the public key of a given private key
-                fn sk_to_pk(sk: &PrivateKey) -> PublicKey {
-                    <$dhkex as DhKeyExchange>::sk_to_pk(sk)
-                }
-
                 const KEM_ID: u16 = $kem_id;

                 /// Deterministically derives a keypair from the given input keying material
@@ -217,6 +212,11 @@ macro_rules! impl_dhkem {
                     <$dhkex as DhKeyExchange>::derive_keypair::<$kdf>(&suite_id, ikm)
                 }

+                /// Computes the public key of a given private key
+                fn sk_to_pk(sk: &PrivateKey) -> PublicKey {
+                    <$dhkex as DhKeyExchange>::sk_to_pk(sk)
+                }
+
                 // Runs encap_with_eph using a random ephemeral key
                 fn encap<R: CryptoRng + RngCore>(
                     pk_recip: &Self::PublicKey,
```

**Comment by rozbb** [comment]
Bump. If you want, I can just do this in a separate PR and credit you in the merge.

**Comment by ycscaly** [comment]
Should be good now

**Comment by rozbb** [comment]
Thank you!

**Pull request merged**
